"""Slice a shared spec file down to its notification content, per revision.

Used as a git-filter-repo --file-info-callback so the carried files keep their
real commit lineage while their content stays scoped to notifications. Section
boundaries move across 193 commits, so selection is by KEYWORD MATCH rather than
by fixed section numbers -- that way the slice tracks the file as it evolves.
"""
import re

KEEP_WHOLE = {
    b"notification-ports.md",
    b"notifications.md",
    b"notification-flow.excalidraw",
}

SLICE = {
    b"research.md", b"spec.md", b"plan.md",
    b"tasks.md", b"data-model.md", b"quickstart.md",
}

RENAME = {
    b"specs/001-contextengine-mvp/contracts/notification-ports.md":
        b"specs/001-notification-core/contracts/notification-ports.md",
    b"specs/001-contextengine-mvp/diagrams/addition/notification-flow.excalidraw":
        b"specs/001-notification-core/diagrams/notification-flow.excalidraw",
    b"design-system/aisat-intel/pages/notifications.md":
        b"design-system/pages/notifications.md",
    b"design-system/aisat-studio/pages/notifications.md":
        b"design-system/pages/notifications.md",
}
for _b in (b"research.md", b"spec.md", b"plan.md", b"tasks.md",
           b"data-model.md", b"quickstart.md"):
    RENAME[b"specs/001-contextengine-mvp/" + _b] = b"specs/001-notification-core/" + _b

# Notification vocabulary. Deliberately a little generous: email and DLQ are
# notification concerns here, and over-including context beats dropping the
# paragraph that explains a decision.
RX = re.compile(
    rb"notif|notify|unread|inbox|broadcast|digest|coalesc|suppress"
    rb"|dlq|dead[_ ]letter|mailer|unsubscribe|bounce|complaint"
    rb"|\bemail\b|US8|User Story 8|FR-03[2-9]|SC-01[123]",
    re.IGNORECASE,
)
STRONG = re.compile(
    rb"notif|notify|unread|inbox|broadcast|digest|coalesc|dlq|dead[_ ]letter"
    rb"|unsubscribe|suppress|mailer|US8|User Story 8|FR-03[2-9]|SC-01[123]",
    re.IGNORECASE,
)
HEADING = re.compile(rb"^(#{1,4})\s")
LISTISH = re.compile(rb"^\s*(-|\*|\d+\.|\|)\s")

HEADER = (b"<!-- Sliced from the originating product's shared spec file, keeping only\n"
          b"     notification content. Commit lineage is the original file's; see\n"
          b"     PROVENANCE.md. Generated by notifslice.py -- do not hand-edit. -->\n\n")


def slice_markdown(data: bytes) -> bytes:
    lines = data.split(b"\n")
    # preamble = everything before the first heading (title, status line, etc.)
    first = next((i for i, l in enumerate(lines) if HEADING.match(l)), len(lines))
    preamble, rest = lines[:first], lines[first:]

    # split the remainder into heading-led blocks
    blocks, cur = [], []
    for l in rest:
        if HEADING.match(l) and cur:
            blocks.append(cur)
            cur = [l]
        else:
            cur.append(l)
    if cur:
        blocks.append(cur)

    out = list(preamble)
    for blk in blocks:
        body = b"\n".join(blk)
        rows = [l for l in blk[1:] if l.strip()]
        listish = [l for l in rows if LISTISH.match(l)]
        list_dominated = rows and len(listish) * 2 > len(rows)

        if list_dominated:
            # A requirements/task table: keep the heading and ONLY the matching
            # rows. Keeping the block whole because one row matched is what drags
            # the entire product spec across.
            hits = [l for l in blk[1:] if LISTISH.match(l) and RX.search(l)]
            if hits:
                out.append(blk[0])
                out.append(b"")
                out.extend(hits)
                out.append(b"")
            continue

        strong = len(STRONG.findall(body))
        if strong >= 2 or (strong == 1 and len(RX.findall(body)) >= 3):
            out.extend(blk)                      # the section is ABOUT notifications
            continue

        hits = [l for l in blk[1:] if LISTISH.match(l) and RX.search(l)]
        if hits:
            out.append(blk[0])
            out.append(b"")
            out.extend(hits)
            out.append(b"")
    sliced = b"\n".join(out).rstrip() + b"\n"
    return HEADER + sliced


def handle(filename, mode, blob_id, value):
    base = filename.rsplit(b"/", 1)[-1]
    newname = RENAME.get(filename, filename)
    if base in KEEP_WHOLE:
        return (newname, mode, blob_id)
    if base in SLICE:
        data = value.get_contents_by_identifier(blob_id)
        if data is None or value.is_binary(data):
            return (newname, mode, blob_id)
        return (newname, mode, value.insert_file_with_contents(slice_markdown(data)))
    return (None, None, None)
